import type { BlockAppearance, PageAppearance } from "./appearance";
export type { BlockAppearance, PageAppearance } from "./appearance";
export const BLOCK_TYPES = ["profile","text","image","separator","link","socials","video","carousel","before_after","testimonial","faq","map","messenger","download","pricing","catalog","product","countdown","scratch","shoutout","community","event","custom_code","form","booking"] as const;
export type BlockType = typeof BLOCK_TYPES[number];
export type Locale = "ru" | "en";
export type BlockData = {
  title?: string; text?: string; subtitle?: string; url?: string; image?: string; name?: string;
  label?: string; alt?: string; items?: Array<{ id?: string; title?: string; text?: string; url?: string; image?: string; icon?: string; alt?: string }>;
  itemIds?: string[]; beforeImage?: string; afterImage?: string; beforeAlt?: string; afterAlt?: string; endsAt?: string; code?: string;
  address?: string; html?: string; calLink?: string; eventTypeId?: number; fileId?: string;
  price?: number; capacity?: number; location?: string; category?: string; avatar?: string; profession?: string;
};
export type AccessPrice = { oneTime?: number; monthly?: number; currency: string };
export type AccessOffer = { id: string; pageId: string; blockId?: string; scope: "page" | "block"; mode: "one_time" | "monthly"; amount: number; currency: string; revision: number };
export type Block = { id: string; type: BlockType; width: "half" | "full"; hidden: boolean; archived?: boolean; paid: boolean; teaser: string; pricing: AccessPrice; data: BlockData; appearance?: BlockAppearance };
export type PublicationModeration = { status: "active" | "blocked"; reason: string; updatedAt: string; version: number };
export type Capabilities = { payments: boolean; demo: boolean; pilot: boolean; creatorSignup: boolean; calOAuth: boolean };
export type RuntimeReadiness = { mode: "demo" | "pilot" | "real"; ready: boolean; checks: Record<"core" | "legal" | "stripe" | "cal" | "notifications" | "telegram", { configured: boolean; status: "ready" | "demo" | "disabled" | "missing" }> };
export type Page = { id: string; ownerId: string; slug: string; title: string; description: string; locale: Locale; accent: string; appearance?: PageAppearance; blocks: Block[]; paid: boolean; teaser: string; pricing: AccessPrice; publishedAt: string | null; updatedAt: string; revision: number; moderation?: PublicationModeration; slugAliases?: string[]; firstPublishedAt?: string };
export type PublicBlock = Omit<Block,"data"> & { locked: boolean; data?: BlockData };
export type PublicPage = Omit<Page,"blocks" | "ownerId" | "moderation" | "slugAliases"> & { blocks: PublicBlock[]; owner: boolean; demo: boolean; locked?: boolean; capabilities?: Capabilities };
export type User = { id: string; email: string; name: string; locale: Locale; role: "creator" | "buyer"; createdAt: string };
export type CatalogItem = { id: string; ownerId: string; pageId: string; title: string; description: string; kind: "service" | "digital" | "physical" | "ticket"; price: number; currency: string; image?: string; category?: string; stock: number | null; reserved: number; fileId?: string; calLink?: string; eventTypeId?: number; shipping: Array<{ country: string; amount: number }>; createdAt: string };
export type Contact = { id: string; ownerId: string; email: string; name: string; notes: string; createdAt: string; updatedAt: string };
export type Opportunity = { id: string; ownerId: string; pageId: string; blockId?: string; contactId: string; source: "form" | "booking" | "purchase"; status: "new" | "booked" | "paid" | "closed"; message: string; convertedAt: string | null; createdAt: string; test: boolean };
export type Booking = { id: string; ownerId: string; pageId: string; contactId: string; opportunityId: string; buyerId?: string; itemId?: string; providerId?: string; title: string; startAt: string; endAt: string; timezone: string; status: "confirmed" | "cancelled"; version: number; createdAt: string; test: boolean };
export type Order = { id: string; ownerId: string; pageId: string; buyerId: string; contactId: string; opportunityId: string; itemId?: string; blockId?: string; bookingId?: string; scope: "page" | "block" | "item"; title: string; mode: "one_time" | "monthly"; quantity: number; amount: number; shippingAmount: number; currency: string; status: "pending" | "paid" | "expired" | "failed" | "refunded" | "disputed"; fulfillment: "unfulfilled" | "processing" | "shipped" | "delivered"; tracking?: string; shippingAddress?: { name: string; line1: string; city: string; postalCode: string; country: string }; stripeSessionId?: string; stripePaymentId?: string; stripeAccountId?: string; subscriptionId?: string; expiresAt: string; createdAt: string; paidAt?: string; test: boolean };
export type Subscription = { id: string; ownerId: string; buyerId: string; pageId: string; blockId?: string; scope: "page" | "block"; status: "active" | "past_due" | "cancelled"; paidThrough: string; cancelAtPeriodEnd: boolean; stripeId?: string; stripeAccountId?: string; orderId: string; updatedAt: string };
export type Entitlement = { id: string; ownerId: string; buyerId: string; pageId: string; blockId?: string; itemId?: string; scope: "page" | "block" | "item"; orderId: string; subscriptionId?: string; status: "active" | "revoked" | "suspended"; expiresAt: string | null; createdAt: string };
export type TimelineEvent = { id: string; ownerId: string; contactId: string; kind: string; title: string; createdAt: string; referenceId?: string };
export type Integration = { id: string; ownerId: string; stripeAccountId?: string; stripeReady?: boolean; calApiKeyEncrypted?: string; calAccessTokenEncrypted?: string; calRefreshTokenEncrypted?: string; calTokenExpiresAt?: string; calWebhookSecretEncrypted?: string; calLink?: string; telegramChatId?: string; updatedAt: string };
export type AnalyticsSource = "direct" | "search" | "social" | "ai" | "referral" | "unknown";
export type AnalyticsDevice = "mobile" | "tablet" | "desktop" | "unknown";
export type AnalyticsAction = "page_access" | "block_access" | "form_open" | "form_submit" | "booking_start" | "booking_confirmed";
export type AnalyticsEvent = { id: string; ownerId: string; pageId: string; kind: "view" | "click" | "notification_failed" | "payment_failed"; visitorId: string; createdAt: string; test: boolean; blockId?: string; action?: AnalyticsAction; source?: AnalyticsSource; device?: AnalyticsDevice; isBot?: boolean; isOwner?: boolean };
export type AnalyticsDays = 7 | 30 | 90;
export type AnalyticsReport = {
  days: AnalyticsDays; startAt: string; endAt: string; timezone: "UTC"; demo: boolean; hasPublishedPage: boolean;
  summary: { views: number; visitors: number; clicks: number; engagedVisitors: number; clickRate: number | null; leads: number; bookings: number; paidOrders: number; conversions: number; repeatContacts: number; formOpens: number; formSubmits: number; bookingStarts: number; bookingConfirmed: number; revenueByCurrency: Record<string, number> };
  daily: Array<{ date: string; views: number; visitors: number; clicks: number; conversions: number }>;
  sources: Array<{ key: AnalyticsSource; views: number; share: number }>;
  devices: Array<{ key: AnalyticsDevice; views: number; share: number }>;
  blocks: Array<{ id: string; title: string; type: BlockType; clicks: number; visitors: number }>;
  excluded: { testEvents: number; automatedEvents: number; ownerEvents: number };
};
export type Asset = { id: string; ownerId: string; pageId: string; filename: string; mime: string; path: string; size: number; createdAt: string };
export type WebhookEvent = { id: string; provider: "stripe" | "cal"; processedAt: string };
export type Notification = { id: string; ownerId: string; bookingId?: string; recipient: string; kind: string; status: "pending" | "sent" | "failed"; error?: string; scheduledAt: string; createdAt: string; test: boolean };
export type AdminAuditEvent = { id: string; actorId: string; action: "publication.block" | "publication.restore"; pageId: string; reason: string; createdAt: string; before: "active" | "blocked"; after: "active" | "blocked" };
export type CreatorInvite = { id: string; email: string; createdAt: string; expiresAt: string; createdBy: string; acceptedBy?: string; acceptedAt?: string; revokedAt?: string };
export type DatabaseState = { users: User[]; pages: Page[]; publishedPages: Page[]; items: CatalogItem[]; contacts: Contact[]; opportunities: Opportunity[]; bookings: Booking[]; orders: Order[]; subscriptions: Subscription[]; entitlements: Entitlement[]; timeline: TimelineEvent[]; integrations: Integration[]; analytics: AnalyticsEvent[]; assets: Asset[]; webhooks: WebhookEvent[]; notifications: Notification[]; adminAudit: AdminAuditEvent[]; creatorInvites: CreatorInvite[] };
export type CheckoutInput = { pageId: string; scope: "page" | "block" | "item"; blockId?: string; itemId?: string; bookingId?: string; mode: "one_time" | "monthly"; quantity?: number; country?: string; shippingAddress?: Order["shippingAddress"] };
export type DashboardData = { user: User; page: Page; items: CatalogItem[]; contacts: Contact[]; opportunities: Opportunity[]; bookings: Booking[]; orders: Order[]; timeline: TimelineEvent[]; integration: { stripeConnected: boolean; stripeReady: boolean; calConnected: boolean; calLink: string; telegramConnected: boolean }; metrics: { views: number; clicks: number; conversions: number; northStar: number; revenue: number; revenueByCurrency?: Record<string, number>; repeatContacts: number; activePages: number }; diagnostics?: { activatedWithin24h: boolean; paymentFailures: number; notificationFailures: number }; demo: boolean; capabilities?: Capabilities; readiness?: RuntimeReadiness };
