"use client";
import { useEffect, useMemo, useState } from "react";
import type { Locale } from "@/lib/types";
import { groupBookingSlots, type BookingSlot } from "@/lib/booking-slots";
import { normalizeBookingResult, type BookingApiResult } from "@/lib/commerce";
import { apiJson, toErrorMessage } from "./api";
import { Icon } from "./pager-icon";
export function BookingPicker({ pageId, slug, blockId, itemId, locale, demo = false, name: initialName = "", email: initialEmail = "", onBooked, onError }: { pageId: string; slug: string; blockId: string; itemId?: string; locale: Locale; authenticated?: boolean; demo?: boolean; name?: string; email?: string; onRequireAuth?: (returnTo: string) => void; onBooked: (result: import("@/lib/commerce").ConfirmedBookingResult) => void; onError?: (message: string) => void }) {
  const timezone = useMemo(() => Intl.DateTimeFormat().resolvedOptions().timeZone || "UTC", []);
  const [slots, setSlots] = useState<BookingSlot[]>([]); const [selected, setSelected] = useState(""); const [selectedDay, setSelectedDay] = useState(""); const [name, setName] = useState(initialName); const [email, setEmail] = useState(initialEmail); const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const days = useMemo(() => groupBookingSlots(slots, locale, timezone), [slots, locale, timezone]);
  const activeDay = days.find(day => day.id === selectedDay) ?? days[0];
  useEffect(() => { const start = new Date(Date.now() + 60 * 60_000); start.setMinutes(0, 0, 0); const end = new Date(start.getTime() + 7 * 86400_000); let active = true; void apiJson<{ slots: BookingSlot[] }>(`/api/public/${encodeURIComponent(slug)}/slots?blockId=${encodeURIComponent(blockId)}${itemId ? `&itemId=${encodeURIComponent(itemId)}` : ""}&start=${encodeURIComponent(start.toISOString())}&end=${encodeURIComponent(end.toISOString())}&timezone=${encodeURIComponent(timezone)}`).then(result => { if (active) setSlots(result.slots); }).catch(err => { if (active) setError(toErrorMessage(err, locale === "ru" ? "Свободное время пока недоступно." : "Available times are not available yet.")); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [slug, blockId, itemId, timezone, locale]);
  const submit = async () => { if (!selected || !name.trim() || !email.trim()) return; setBusy(true); setError(""); try { const result = await apiJson<BookingApiResult>("/api/bookings", { method: "POST", body: JSON.stringify({ pageId, blockId, itemId, name: name.trim(), email: email.trim(), startAt: selected, timezone, idempotencyKey: crypto.randomUUID() }) }); const confirmed = normalizeBookingResult(result); if (confirmed) onBooked(confirmed); else setError(locale === "ru" ? "Запрос отправлен на подтверждение провайдеру. Повторите через минуту." : "The provider is confirming this request. Try again in a minute."); } catch (err) { const message = toErrorMessage(err); setError(message); onError?.(message); } finally { setBusy(false); } };
  const selection = activeDay?.slots.find(slot => slot.startAt === selected);
  return <div className="booking-picker"><label className="field"><span className="side-label">{locale === "ru" ? "Имя" : "Name"}</span><input value={name} onChange={event => setName(event.target.value)} autoComplete="name" /></label><label className="field"><span className="side-label">Email</span><input type="email" value={email} onChange={event => setEmail(event.target.value)} disabled={Boolean(initialEmail)} autoComplete="email" /></label>{loading ? <div className="notice"><Icon name="Activity" size={16} />{locale === "ru" ? "Загружаем свободное время…" : "Loading available times…"}</div> : days.length && activeDay ? <div className="slot-picker"><div className="slot-days" role="tablist" aria-label={locale === "ru" ? "Дни с доступным временем" : "Days with available times"}>{days.map(day => <button key={day.id} id={`slot-day-${day.id}`} type="button" role="tab" aria-selected={activeDay.id === day.id} aria-controls={`slot-panel-${day.id}`} className={activeDay.id === day.id ? "slot-day selected" : "slot-day"} onClick={() => { setSelectedDay(day.id); if (!day.slots.some(slot => slot.startAt === selected)) setSelected(""); }}>{day.label}</button>)}</div><div id={`slot-panel-${activeDay.id}`} role="tabpanel" aria-labelledby={`slot-day-${activeDay.id}`} className="slot-list"><span className="sr-only">{locale === "ru" ? "Свободное время" : "Available times"}</span>{activeDay.slots.map(slot => <button key={slot.startAt} type="button" className={`slot-button ${selected === slot.startAt ? "selected" : ""}`} aria-pressed={selected === slot.startAt} onClick={() => setSelected(slot.startAt)}><strong>{slot.timeLabel}</strong><span>{locale === "ru" ? "до" : "to"} {slot.endTimeLabel}</span></button>)}</div></div> : <div className="notice">{locale === "ru" ? "Свободных вариантов нет. Оставьте заявку автору." : "No times are available. Send the creator an enquiry."}</div>}<p className="slot-selection" aria-live="polite">{selection ? (locale === "ru" ? `Выбрано: ${activeDay.label}, ${selection.timeLabel}` : `Selected: ${activeDay.label}, ${selection.timeLabel}`) : (locale === "ru" ? "Выберите день и время" : "Choose a day and time")}</p><div className="notice"><Icon name="Clock3" size={16} />{locale === "ru" ? `Время показано для ${timezone}` : `Times shown for ${timezone}`}{demo && <span className="demo-pill">DEMO</span>}</div><button className="button button-primary" type="button" onClick={() => void submit()} disabled={busy || loading || !selected || !name.trim() || !email.trim()}>{locale === "ru" ? "Подтвердить время" : "Confirm time"}</button>{error && <div className="notice error-notice" role="alert"><Icon name="Info" size={16} />{error}</div>}</div>;
}
