"use client";
import { useEffect, useMemo, useState } from "react";
import type { Locale } from "@/lib/types";
import { normalizeBookingResult, type BookingApiResult } from "@/lib/commerce";
import { apiJson, toErrorMessage } from "./api";
import { Icon } from "./pager-icon";
type Slot = { startAt: string; endAt: string };
export function BookingPicker({ pageId, slug, blockId, itemId, locale, demo = false, name: initialName = "", email: initialEmail = "", onBooked, onError }: { pageId: string; slug: string; blockId: string; itemId?: string; locale: Locale; authenticated?: boolean; demo?: boolean; name?: string; email?: string; onRequireAuth?: (returnTo: string) => void; onBooked: (result: import("@/lib/commerce").ConfirmedBookingResult) => void; onError?: (message: string) => void }) {
  const timezone = useMemo(() => Intl.DateTimeFormat().resolvedOptions().timeZone || "UTC", []);
  const [slots, setSlots] = useState<Slot[]>([]); const [selected, setSelected] = useState(""); const [name, setName] = useState(initialName); const [email, setEmail] = useState(initialEmail); const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { const start = new Date(Date.now() + 60 * 60_000); start.setMinutes(0, 0, 0); const end = new Date(start.getTime() + 7 * 86400_000); let active = true; void apiJson<{ slots: Slot[] }>(`/api/public/${encodeURIComponent(slug)}/slots?blockId=${encodeURIComponent(blockId)}${itemId ? `&itemId=${encodeURIComponent(itemId)}` : ""}&start=${encodeURIComponent(start.toISOString())}&end=${encodeURIComponent(end.toISOString())}&timezone=${encodeURIComponent(timezone)}`).then(result => { if (active) setSlots(result.slots); }).catch(err => { if (active) setError(toErrorMessage(err, locale === "ru" ? "Свободное время пока недоступно." : "Available times are not available yet.")); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [slug, blockId, itemId, timezone, locale]);
  const submit = async () => { if (!selected || !name.trim() || !email.trim()) return; setBusy(true); setError(""); try { const result = await apiJson<BookingApiResult>("/api/bookings", { method: "POST", body: JSON.stringify({ pageId, blockId, itemId, name: name.trim(), email: email.trim(), startAt: selected, timezone, idempotencyKey: crypto.randomUUID() }) }); const confirmed = normalizeBookingResult(result); if (confirmed) onBooked(confirmed); else setError(locale === "ru" ? "Запрос отправлен на подтверждение провайдеру. Повторите через минуту." : "The provider is confirming this request. Try again in a minute."); } catch (err) { const message = toErrorMessage(err); setError(message); onError?.(message); } finally { setBusy(false); } };
  return <div className="booking-picker"><label className="field"><span className="side-label">{locale === "ru" ? "Имя" : "Name"}</span><input value={name} onChange={event => setName(event.target.value)} autoComplete="name" /></label><label className="field"><span className="side-label">Email</span><input type="email" value={email} onChange={event => setEmail(event.target.value)} disabled={Boolean(initialEmail)} autoComplete="email" /></label><div className="slot-list" aria-label={locale === "ru" ? "Свободное время" : "Available times"}>{loading ? <div className="notice"><Icon name="Activity" size={16} />{locale === "ru" ? "Загружаем свободное время…" : "Loading available times…"}</div> : slots.length ? slots.map(slot => <button key={slot.startAt} type="button" className={`slot-button ${selected === slot.startAt ? "selected" : ""}`} onClick={() => setSelected(slot.startAt)}><strong>{new Date(slot.startAt).toLocaleDateString(locale === "ru" ? "ru-RU" : "en-US", { weekday: "short", month: "short", day: "numeric" })}</strong><span>{new Date(slot.startAt).toLocaleTimeString(locale === "ru" ? "ru-RU" : "en-US", { hour: "2-digit", minute: "2-digit" })}</span></button>) : <div className="notice">{locale === "ru" ? "Свободных вариантов нет. Оставьте заявку автору." : "No times are available. Send the creator an enquiry."}</div>}</div><div className="notice"><Icon name="Clock3" size={16} />{locale === "ru" ? `Время показано для ${timezone}` : `Times shown for ${timezone}`}{demo && <span className="demo-pill">DEMO</span>}</div><button className="button button-primary" type="button" onClick={() => void submit()} disabled={busy || loading || !selected || !name.trim() || !email.trim()}>{locale === "ru" ? "Подтвердить время" : "Confirm time"}</button>{error && <div className="notice error-notice" role="alert"><Icon name="Info" size={16} />{error}</div>}</div>;
}
